Big update
1. Add some variables to configure.ac
2. Restructure Makefile
3. Add en_US locale

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -2,6 +2,7 @@
 
 prefix         =    @prefix@
 exec_prefix    =    @exec_prefix@
+# Каталог, куда будет установлена программа
 bindir         =    @bindir@
 sbindir        =    @sbindir@
 libexecdir     =    @libexecdir@
@@ -22,46 +23,31 @@ dvidir         =    @dvidir@
 pdfdir         =    @pdfdir@
 psdir          =    @psdir@
 
+
 # Makefile for PassGen project
 # Документация с примерами: http://linux.yaroslavl.ru/docs/prog/make_intro_ru.html
 
-AUTHOR          = "Yarkov Aleksey"
-EMAIL           = yarkov_aleksei@mail.ru
-CHARSET         = UTF-8
-LOCALE          = ru_RU
-LICENSE         = MIT
+PACKAGE_NAME    	= "@PACKAGE_NAME@"
+PACKAGE_VERSION 	= "@PACKAGE_VERSION@"
+PACKAGE_URL			= "@PACKAGE_URL@"
+PACKAGE_DESCRIPTION = "@PACKAGE_DESCRIPTION@"
 
-# Каталог, куда будет установлена программа
-INSTALLDIR      = $(bindir)
-
-HELP            = "Usage make:\n\
-\tmake                               - build binary file from source\n \
-\tmake clean                         - clean project folder from *.o, ./bin, etc.\n \
-\tmake distclean                     - clean project folder from ./configure created\n \
-\tmake check                         - run binary with test parameters\n \
-\tmake elang                         - extract localize phrases from source to *.po\n \
-\tmake glang                         - create localize *.mo file from *.po files\n \
-\tmake autodoc                       - generate README.md\n \
-\tsudo make build install=<yes|no>   - build deb package\n \
-\tsudo make install                  - install binary to $(INSTALLDIR)\n \
-\tsudo make uninstall                - uninstall binary from $(INSTALLDIR)"
+PACKAGE_AUTHOR      = "@PACKAGE_AUTHOR@"
+PACKAGE_EMAIL       = @PACKAGE_BUGREPORT@
+PACKAGE_LICENSE   	= "@PACKAGE_LICENSE@"
 
 # Рабочая оболочка
 SHELL           = /bin/bash
-# Имя бинарного файла
-PACKAGE_NAME    = passgen
-# Версия релиза
-PACKAGE_VERSION = "1.0.0"
-# Описание пакета
-DESCRIPTION     = "Console password generator"
 # Зависимости пакета
-DEPENDENCIES    = "mcrypt, libmcrypt-dev"
+DEPENDENCIES    = ""
 # Описание пакета
 DESCRIPTIONFILE = "./description-pak"
 # Каталог для собранного бинарного файла
 BINDIR          = ./bin
 # Каталог для manpage
 MANDIR          = ./man
+# Путь к файлу manpage
+MANFILE			= $(MANDIR)/$(PACKAGE_NAME).1
 # Каталог для установки файлов manpage
 MAN_TARGET      = $(mandir)/man1
 # Каталог для deb пакета
@@ -71,19 +57,25 @@ SRCDIR          = ./source
 # Каталог для файлов локализации
 LOCALEDIR       = ./locale
 # Каталог для установки файлов локализации
-LOCALE_TARGET   = $(localedir)/locale/ru/LC_MESSAGES
-# Файл локализации
-LOCALE_MO       = $(LOCALEDIR)/ru/LC_MESSAGES/$(PACKAGE_NAME).mo
-# Исходник файла локализации
-LOCALE_PO       = $(LOCALEDIR)/ru/LC_MESSAGES/$(PACKAGE_NAME).po
+LOCALE_TARGET   = $(localedir)
+# Список каталогов для локализаций (имя каталога соответствует языку: ru, en, fr и т. п.)
+LOCALES			= $$(find $(LOCALEDIR) -mindepth 1 -maxdepth 1 -type d)
+# Имя файла локализации
+LOCALE_MO       = $(PACKAGE_NAME).mo
+# Имя исходника файла локализации
+LOCALE_PO       = $(PACKAGE_NAME).po
+# Подкаталог для установки файла локализации
+LC_MESSAGES		= LC_MESSAGES
 # Временный файл локализации
-TMP_LOCALE_PO   = $(LOCALEDIR)/ru/$(PACKAGE_NAME).po
+TMP_LOCALE_PO   = /tmp/$(LOCALE_PO)
 # Флаги компилятора
-CFLAGS          = -Wall -std=c99 -fpic -D_XOPEN_SOURCE=600 -lmcrypt
-GCCDEFINES      = -DTEST="TESTDEFINE"
+CFLAGS          = -Wall -std=c99 -fpic -D_XOPEN_SOURCE=600 -I$(SRCDIR)/h
+GCCDEFINES      = -DTEST=TESTDEFINE
 # Файлы и папки, которые удалятся по команде make [dist]clean
-CLEANED         = $(BINDIR) $(DEBDIR) ./*.o ./*.*~
-DISTCLEANED     = $(BINDIR) $(DEBDIR) ./*.m4 ./*.log ./*.scan ./*.status ./autom4te.* ./Makefile ./.fuse_hidden*
+CLEANED         = $(BINDIR) ./*.o ./*.*~
+DISTCLEANED     = $(DEBDIR) ./*.m4 ./*.log ./*.scan ./*.status ./autom4te.* ./Makefile ./.fuse_hidden* ./$(SRCDIR)/h/*.h.in~ ./$(SRCDIR)/h/stamp-h1
+
+CHARSET         = UTF-8
 
 ONELINEOKMSG    = "[$(PACKAGE_NAME)]: TEST - single line: OK"
 ONELINEERRMSG   = "[$(PACKAGE_NAME)]: TEST - single line: ERROR"
@@ -105,8 +97,6 @@ objects := $(patsubst $(SRCDIR)/%.c,%.o,$(wildcard $(SRCDIR)/*.c))
 
 all: $(PACKAGE_NAME)
 	@echo "[$(PACKAGE_NAME)] - Project compiled"
-	@make check
-	@make autodoc
 
 $(PACKAGE_NAME): $(objects)
 	@mkdir -p $(BINDIR)
@@ -119,16 +109,18 @@ $(PACKAGE_NAME): $(objects)
 
 # Запускаем сборку deb пакета
 build:
+#	@test -f $(BINDIR)/$(PACKAGE_NAME) || echo "Not found $(BINDIR)/$(PACKAGE_NAME) file" && exit 1;
 	@mkdir -p $(DEBDIR)
 	@checkinstall \
-	--default --nodoc \
+	--default \
+	--nodoc \
 	--pkgname=$(PACKAGE_NAME) \
 	--pkgrelease=$(PACKAGE_VERSION) \
 	--pkgversion=$$(date +%Y%m%d) \
 	--pkgsource=$(SRCDIR) \
 	--pakdir=$(DEBDIR) \
-	--maintainer=$(EMAIL) \
-	--pkglicense=$(LICENSE) \
+	--maintainer=$(PACKAGE_EMAIL) \
+	--pkglicense=$(PACKAGE_LICENSE) \
 	--requires=$(DEPENDENCIES) \
 	--install=$$(test ${install} == 'yes' && echo -n 'yes' || echo -n 'no') \
 	--gzman=yes \
@@ -136,6 +128,7 @@ build:
 	--deldesc=no \
 	--delspec=yes \
 	--backup=no \
+	--autodoinst=yes \
 	--strip=yes
 
 clean:
@@ -147,66 +140,72 @@ distclean:
 	@echo "[$(PACKAGE_NAME)] - Dist cleaned"
 
 install:
-	@install -D $(BINDIR)/$(PACKAGE_NAME) $(INSTALLDIR)
-	@install -D $(LOCALE_MO) $(LOCALE_TARGET)
-	@install -D -g 0 -o 0 -m 0644 $(MANDIR)/$(PACKAGE_NAME).1 $(MAN_TARGET)
+	@install -D $(BINDIR)/$(PACKAGE_NAME) $(bindir)
+	@for localedir in $(LOCALES); do \
+		l=$$(basename $$localedir) && \
+		install -D $$localedir/$(LC_MESSAGES)/$(LOCALE_MO) $(LOCALE_TARGET)/$(PACKAGE_NAME)/$$l/$(LC_MESSAGES); \
+	done
+	@install -D -g 0 -o 0 -m 0644 $(MANFILE) $(MAN_TARGET)
 	@gzip --force $(MAN_TARGET)/$(PACKAGE_NAME).1
 	@echo "[$(PACKAGE_NAME)] - installed to $$(which $(PACKAGE_NAME))"
 
 uninstall:
-	@rm -rf $(INSTALLDIR)/$(PACKAGE_NAME)
-	@echo "[$(PACKAGE_NAME)] - uninstalled from $$(which $(PACKAGE_NAME))"
+	@rm -rf $(bindir)/$(PACKAGE_NAME)
+	@rm -rf $(MAN_TARGET)/$(PACKAGE_NAME).*
+	@rm -rf $(LOCALE_TARGET)/$(PACKAGE_NAME)
+	@echo "[$(PACKAGE_NAME)] - uninstalled"
 
 check:
 	@test $$($(BINDIR)/$(PACKAGE_NAME) -l20 -ds | wc -m) == '21' && echo $(ONELINEOKMSG) || echo $(ONELINEERRMSG)
 	@test $$($(BINDIR)/$(PACKAGE_NAME) -l20 -ds -c5 | wc -l) == '5' && echo $(MULTILINEOKMSG) || echo $(MULTILINEERRMSG)
 
 # Сканирует исходники на предмет использования gettext
-# и создает файл локализации ./locale/ru/passgen.po.
+# и создает файл локализации ./locale/*/passgen.po.
 # Если файл существует, то аккуратно обновляет его,
 # сохраняя резервную копию.
 elang:
-	@xgettext \
-	--no-wrap \
-	--force-po \
-	--copyright-holder=$(AUTHOR) \
-	--msgid-bugs-address=$(EMAIL) \
-	--default-domain=$(PACKAGE_NAME) \
-	--package-name=$(PACKAGE_NAME) \
-	--package-version=$(PACKAGE_VERSION) \
-	--output-dir=/tmp \
-	--language=C \
-	--from-code=$(CHARSET) \
-	--keyword=_ \
-	$(SRCDIR)/*.c $(SRCDIR)/**/*.h
-	@msgmerge -N -U \
-	--no-wrap \
-	--suffix=.backup \
-	--backup=numbered \
-	$(TMP_LOCALE_PO) \
-	/tmp/$(PACKAGE_NAME).po
-	@echo -e "Add translate to file $(LOCALEDIR)/ru/$(PACKAGE_NAME).po and run command\n\n\tmake glang"
+	@for localedir in $(LOCALES); do \
+		[ -d $$localedir/$(LC_MESSAGES) ] || mkdir -p $$localedir/$(LC_MESSAGES) && \
+		[ -f $$localedir/$(LC_MESSAGES)/$(LOCALE_PO) ] || touch $$localedir/$(LC_MESSAGES)/$(LOCALE_PO) && \
+		xgettext \
+		--no-wrap \
+		--force-po \
+		--add-location \
+		--join-existing \
+		--copyright-holder=$(PACKAGE_AUTHOR) \
+		--msgid-bugs-address=$(PACKAGE_EMAIL) \
+		--default-domain=$(PACKAGE_NAME) \
+		--package-name=$(PACKAGE_NAME) \
+		--package-version=$(PACKAGE_VERSION) \
+		--output-dir=/tmp \
+		--language=C \
+		--from-code=$(CHARSET) \
+		--keyword=_ \
+		$(SRCDIR)/*.c $(SRCDIR)/**/*.h && \
+		msginit \
+		--no-wrap \
+		--no-translator \
+		--input=/tmp/$(LOCALE_PO) \
+		--output-file=$$localedir/$(LC_MESSAGES)/$(LOCALE_PO) \
+		--locale=$$(basename $$localedir).$(CHARSET) && \
+		echo -e "Translate $$localedir/$(LC_MESSAGES)/$(LOCALE_PO) and run command\n\n\t$ make glang"; \
+	done
 
-# Создает файл локализации ./locale/ru/LC_MESSAGES/passgen.mo
+# Создает файл локализации ./locale/*/LC_MESSAGES/passgen.mo
 glang:
-	@msginit \
-	--no-wrap \
-	--no-translator \
-	--input=$(TMP_LOCALE_PO) \
-	--output-file=$(LOCALE_PO) \
-	--locale=$(LOCALE)
-	@msgfmt \
-	$(LOCALE_PO) \
-	--output-file=$(LOCALE_MO)
-	@rm -f $(LOCALEDIR)/ru/*.~*~
+	@for localedir in $(LOCALES); do \
+		msgfmt \
+		$$localedir/$(LC_MESSAGES)/$(PACKAGE_NAME).po \
+		--output-file=$$localedir/$(LC_MESSAGES)/$(LOCALE_MO);\
+	done
 
 help:
-	@echo -e $(HELP)
+	@echo -e "`cat ./resource/make/help`"
 
 # Генерируем файл README.md и вставляем в него актуальную информацию
 autodoc:
-	@cat ./.src/1 > ./README.md
+	@cat ./resource/readme/1 > ./README.md
 	@./bin/passgen -h >> ./README.md
-	@cat ./.src/2 >> ./README.md
+	@cat ./resource/readme/2 >> ./README.md
 	@echo -e $(HELP) >> ./README.md
 	@echo "\`\`\`" >> ./README.md
